In [1]:
import pandas as pd
import numpy as np

data_path = 'Impute_misvalues_hanoi.csv'
data = pd.read_csv(data_path)

data.head()

,Date,Hour,Waterlevel,Average,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,1/1/2008,1,130.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,4,121.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1/1/2008,7,112.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,10,113.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1/1/2008,13,115.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data.drop('Average', axis=1, inplace=True)
data.head()

       Date  Hour  Waterlevel
0  1/1/2008     1       130.0
1       NaN     4       121.0
2  1/1/2008     7       112.0
3       NaN    10       113.5
4  1/1/2008    13       115.0

In [3]:
data.drop_duplicates()

             Date  Hour  Waterlevel
0        1/1/2008     1       130.0
1             NaN     4       121.0
2        1/1/2008     7       112.0
3             NaN    10       113.5
4        1/1/2008    13       115.0
...           ...   ...         ...
29219  12/31/2017    10       144.0
29220  12/31/2017    13       138.0
29221  12/31/2017    16       127.0
29222  12/31/2017    19       116.0
29223  12/31/2017    22       116.0

[24873 rows x 3 columns]

In [4]:
data.isnull().sum()

Date          6264
Hour             0
Waterlevel       0
dtype: int64

In [5]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
data['Date'].fillna(method='ffill', inplace=True)

In [6]:
data.isnull().sum()

Date          0
Hour          0
Waterlevel    0
dtype: int64

In [8]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Format the 'Date' column to the desired format 'MM/DD/YYYY' without time information
data['Date'] = data['Date'].dt.strftime('%m/%d/%Y')
data.head()

         Date  Hour  Waterlevel
0  01/01/2008     1       130.0
1  01/01/2008     4       121.0
2  01/01/2008     7       112.0
3  01/01/2008    10       113.5
4  01/01/2008    13       115.0

In [ ]:
data.to_csv('Impute_misvalues_hanoi1.csv')