In [1]:
import pandas as pd

data_path = 'Impute_misvalues_vuquang.csv'
data = pd.read_csv(data_path)

data.head()

       Date  Hour  Water.lever   X
0  1/1/2008     1        937.0 NaN
1       NaN     4        933.5 NaN
2  1/1/2008     7        930.0 NaN
3       NaN    10        926.5 NaN
4  1/1/2008    13        923.0 NaN

In [2]:
data.drop('X', axis=1, inplace=True)

In [3]:
data.head()

       Date  Hour  Water.lever
0  1/1/2008     1        937.0
1       NaN     4        933.5
2  1/1/2008     7        930.0
3       NaN    10        926.5
4  1/1/2008    13        923.0

In [4]:
data.drop_duplicates()

             Date  Hour  Water.lever
0        1/1/2008     1        937.0
1             NaN     4        933.5
2        1/1/2008     7        930.0
3             NaN    10        926.5
4        1/1/2008    13        923.0
...           ...   ...          ...
29219  12/31/2017    10        611.0
29220  12/31/2017    13        624.0
29221  12/31/2017    16        640.0
29222  12/31/2017    19        653.0
29223  12/31/2017    22        658.0

[29132 rows x 3 columns]

In [5]:
data.isnull().sum()

Date           584
Hour             0
Water.lever      0
dtype: int64

In [6]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')
data['Date'].fillna(method='ffill', inplace=True)

In [7]:
data.head()

        Date  Hour  Water.lever
0 2008-01-01     1        937.0
1 2008-01-01     4        933.5
2 2008-01-01     7        930.0
3 2008-01-01    10        926.5
4 2008-01-01    13        923.0

In [8]:
data.isnull().sum()

Date           0
Hour           0
Water.lever    0
dtype: int64

In [9]:
data['Date'] = pd.to_datetime(data['Date'], errors='coerce')

# Format the 'Date' column to the desired format 'MM/DD/YYYY' without time information
data['Date'] = data['Date'].dt.strftime('%m/%d/%Y')

# Display the first few rows to confirm the format
data.head()

         Date  Hour  Water.lever
0  01/01/2008     1        937.0
1  01/01/2008     4        933.5
2  01/01/2008     7        930.0
3  01/01/2008    10        926.5
4  01/01/2008    13        923.0

In [10]:
data.to_csv('Impute_misvalues_vuquang1.csv')