In [53]:
from keras.layers import Dense, Dropout
from keras.models import Sequential
from keras.optimizers import Adam
import pandas as pd
import tensorflow as tf
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import SGD, Adam , Nadam

import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,accuracy_score
from keras.callbacks import Callback, EarlyStopping
from tensorflow.keras.utils import to_categorical

In [54]:
file_path = '/content/drive/MyDrive/Colab Notebooks/AKH_WQI.csv'
df = pd.read_csv(file_path)
df.head()

,PH,Temp,Turbidity,TSS,BOD5,COD,DO,Amoni,Phosphat,Coliforms,WQI
0,7.2,27.8,60.0,210.0,3.20,6.6,7.2,0.35,0.84,2600,49.68
1,7.1,27.6,65.0,180.0,3.15,6.8,7.7,0.88,0.95,4700,65.34
2,7.3,27.7,65.0,195.0,3.68,7.8,7.0,2.25,1.36,8500,51.53
3,7.1,27.5,70.0,180.0,3.50,6.2,6.7,2.33,1.41,7500,55.26
4,6.9,27.5,80.0,100.0,3.84,6.8,6.4,1.87,2.74,9500,49.51

In [55]:
scaler = StandardScaler()
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

X = scaler.fit_transform(X)

In [56]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

In [57]:
model = Sequential()
model.add(Dense(units=128, activation="relu", input_shape=(X_train.shape[1],), kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=64, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=32, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation="relu", kernel_regularizer=l2(0.01)))

model.compile(optimizer=Adam(learning_rate=0.01), loss='mean_squared_error', metrics=['mae'])

model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_24 (Dense)            (None, 128)               1408

 dropout_18 (Dropout)        (None, 128)               0

 dense_25 (Dense)            (None, 64)                8256

 dropout_19 (Dropout)        (None, 64)                0

 dense_26 (Dense)            (None, 32)                2080

 dropout_20 (Dropout)        (None, 32)                0

 dense_27 (Dense)            (None, 1)                 33

=================================================================
Total params: 11777 (46.00 KB)
Trainable params: 11777 (46.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [58]:
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

model.fit(X_train, y_train, epochs=100, batch_size=20, validation_data=(X_val, y_val))

Epoch 1/100
23/23 [==============================] - 2s 24ms/step - loss: 1169.1536 - mae: 27.3851 - val_loss: 784.3421 - val_mae: 23.7979
Epoch 2/100
23/23 [==============================] - 0s 6ms/step - loss: 480.5780 - mae: 17.0060 - val_loss: 312.7021 - val_mae: 14.5380
Epoch 3/100
23/23 [==============================] - 0s 5ms/step - loss: 369.8627 - mae: 15.1512 - val_loss: 290.2536 - val_mae: 13.2786
Epoch 4/100
23/23 [==============================] - 0s 5ms/step - loss: 362.5857 - mae: 14.9584 - val_loss: 272.4971 - val_mae: 13.0209
Epoch 5/100
23/23 [==============================] - 0s 6ms/step - loss: 321.0463 - mae: 14.0822 - val_loss: 307.8026 - val_mae: 14.5702
Epoch 6/100
23/23 [==============================] - 0s 6ms/step - loss: 355.8994 - mae: 14.8216 - val_loss: 300.8928 - val_mae: 14.2317
Epoch 7/100
23/23 [==============================] - 0s 5ms/step - loss: 306.5150 - mae: 13.3625 - val_loss: 282.0363 - val_mae: 12.8957
Epoch 8/100
23/23 [==============================] - 0s 5ms/step - loss: 326.2586 - mae: 14.2470 - val_loss: 316.2449 - val_mae: 14.6007
Epoch 9/100
23/23 [==============================] - 0s 4ms/step - loss: 323.7952 - mae: 14.0659 - val_loss: 294.8686 - val_mae: 13.9113
Epoch 10/100
23/23 [==============================] - 0s 5ms/step - loss: 377.6135 - mae: 14.9108 - val_loss: 301.8849 - val_mae: 14.5802
Epoch 11/100
23/23 [==============================] - 0s 5ms/step - loss: 357.2633 - mae: 14.6297 - val_loss: 433.5916 - val_mae: 17.6136
Epoch 12/100
23/23 [==============================] - 0s 5ms/step - loss: 321.5111 - mae: 13.6572 - val_loss: 268.7859 - val_mae: 13.2683
Epoch 13/100
23/23 [==============================] - 0s 7ms/step - loss: 307.4975 - mae: 13.6636 - val_loss: 320.6599 - val_mae: 14.9520
Epoch 14/100
23/23 [==============================] - 0s 6ms/step - loss: 312.5299 - mae: 13.7989 - val_loss: 279.8924 - val_mae: 13.6368
Epoch 15/100
23/23 [==============================] - 0s 5ms/step - loss: 306.4648 - mae: 13.2073 - val_loss: 288.5994 - val_mae: 13.7579
Epoch 16/100
23/23 [==============================] - 0s 7ms/step - loss: 344.2528 - mae: 14.3982 - val_loss: 287.7136 - val_mae: 13.5614
Epoch 17/100
23/23 [==============================] - 0s 5ms/step - loss: 311.5816 - mae: 13.6441 - val_loss: 267.9047 - val_mae: 12.8864
Epoch 18/100
23/23 [==============================] - 0s 6ms/step - loss: 309.5598 - mae: 13.6477 - val_loss: 366.3888 - val_mae: 15.9949
Epoch 19/100
23/23 [==============================] - 0s 6ms/step - loss: 292.7776 - mae: 13.0211 - val_loss: 257.2668 - val_mae: 12.3019
Epoch 20/100
23/23 [==============================] - 0s 6ms/step - loss: 271.7026 - mae: 12.4089 - val_loss: 312.7659 - val_mae: 14.4445
Epoch 21/100
23/23 [==============================] - 0s 6ms/step - loss: 276.7285 - mae: 12.8360 - val_loss: 326.9971 - val_mae: 14.7470
Epoch 22/100
23/23 [==============================] - 0s 4ms/step - loss: 284.5879 - mae: 12.9292 - val_loss: 268.0261 - val_mae: 13.0516
Epoch 23/100
23/23 [==============================] - 0s 5ms/step - loss: 280.7138 - mae: 12.7816 - val_loss: 284.4788 - val_mae: 13.8966
Epoch 24/100
23/23 [==============================] - 0s 5ms/step - loss: 249.4198 - mae: 11.9629 - val_loss: 302.4060 - val_mae: 14.0916
Epoch 25/100
23/23 [==============================] - 0s 6ms/step - loss: 278.4112 - mae: 12.7455 - val_loss: 310.4992 - val_mae: 14.0587
Epoch 26/100
23/23 [==============================] - 0s 6ms/step - loss: 272.4784 - mae: 12.4794 - val_loss: 327.5695 - val_mae: 14.5986
Epoch 27/100
23/23 [==============================] - 0s 8ms/step - loss: 258.5227 - mae: 12.3896 - val_loss: 289.3498 - val_mae: 13.4575
Epoch 28/100
23/23 [==============================] - 0s 7ms/step - loss: 270.8166 - mae: 12.6232 - val_loss: 303.2107 - val_mae: 13.9569
Epoch 29/100
23/23 [==============================] - 0s 6ms/step - loss: 290.1147 - mae: 12.9453 - val_loss: 339.9931 - val_mae: 14.9693
Epoch 30/100
23/23 [==============================] - 0s 6ms/step - loss: 259.3397 - mae: 12.3925 - val_loss: 302.1332 - val_mae: 13.9637
Epoch 31/100
23/23 [==============================] - 0s 6ms/step - loss: 263.7335 - mae: 12.4894 - val_loss: 303.0445 - val_mae: 14.2694
Epoch 32/100
23/23 [==============================] - 0s 6ms/step - loss: 267.7456 - mae: 12.5285 - val_loss: 489.5516 - val_mae: 17.9094
Epoch 33/100
23/23 [==============================] - 0s 7ms/step - loss: 276.9710 - mae: 12.4518 - val_loss: 312.0879 - val_mae: 14.1635
Epoch 34/100
23/23 [==============================] - 0s 8ms/step - loss: 249.1068 - mae: 11.8683 - val_loss: 381.4914 - val_mae: 15.9680
Epoch 35/100
23/23 [==============================] - 0s 6ms/step - loss: 261.7502 - mae: 12.2182 - val_loss: 291.5712 - val_mae: 13.6046
Epoch 36/100
23/23 [==============================] - 0s 6ms/step - loss: 245.9812 - mae: 11.7073 - val_loss: 308.5393 - val_mae: 13.7418
Epoch 37/100
23/23 [==============================] - 0s 6ms/step - loss: 228.8035 - mae: 11.1258 - val_loss: 411.9033 - val_mae: 16.5335
Epoch 38/100
23/23 [==============================] - 0s 5ms/step - loss: 259.0484 - mae: 11.9959 - val_loss: 281.5753 - val_mae: 13.7184
Epoch 39/100
23/23 [==============================] - 0s 6ms/step - loss: 261.7835 - mae: 12.2043 - val_loss: 255.7341 - val_mae: 12.3573
Epoch 40/100
23/23 [==============================] - 0s 7ms/step - loss: 243.7187 - mae: 11.9090 - val_loss: 266.0538 - val_mae: 12.1849
Epoch 41/100
23/23 [==============================] - 0s 6ms/step - loss: 245.8938 - mae: 11.9128 - val_loss: 488.1264 - val_mae: 18.0876
Epoch 42/100
23/23 [==============================] - 0s 5ms/step - loss: 328.8778 - mae: 13.7548 - val_loss: 257.3260 - val_mae: 11.9492
Epoch 43/100
23/23 [==============================] - 0s 5ms/step - loss: 234.4770 - mae: 11.6134 - val_loss: 313.1923 - val_mae: 14.5387
Epoch 44/100
23/23 [==============================] - 0s 5ms/step - loss: 218.1303 - mae: 11.2825 - val_loss: 340.9244 - val_mae: 15.1746
Epoch 45/100
23/23 [==============================] - 0s 6ms/step - loss: 268.6920 - mae: 12.4482 - val_loss: 326.1855 - val_mae: 14.4373
Epoch 46/100
23/23 [==============================] - 0s 8ms/step - loss: 243.1177 - mae: 11.9957 - val_loss: 297.3407 - val_mae: 13.7022
Epoch 47/100
23/23 [==============================] - 0s 7ms/step - loss: 225.8734 - mae: 11.3620 - val_loss: 331.8412 - val_mae: 14.8006
Epoch 48/100
23/23 [==============================] - 0s 6ms/step - loss: 218.6969 - mae: 11.1667 - val_loss: 278.0865 - val_mae: 13.1311
Epoch 49/100
23/23 [==============================] - 0s 6ms/step - loss: 227.2766 - mae: 11.4909 - val_loss: 266.0801 - val_mae: 12.4203
Epoch 50/100
23/23 [==============================] - 0s 5ms/step - loss: 219.3283 - mae: 11.2273 - val_loss: 264.3076 - val_mae: 11.9519
Epoch 51/100
23/23 [==============================] - 0s 6ms/step - loss: 269.9604 - mae: 12.3247 - val_loss: 356.0754 - val_mae: 15.4444
Epoch 52/100
23/23 [==============================] - 0s 5ms/step - loss: 256.5912 - mae: 12.1537 - val_loss: 296.5463 - val_mae: 13.6039
Epoch 53/100
23/23 [==============================] - 0s 8ms/step - loss: 233.6015 - mae: 11.3684 - val_loss: 269.6193 - val_mae: 12.6128
Epoch 54/100
23/23 [==============================] - 0s 7ms/step - loss: 220.0872 - mae: 11.2701 - val_loss: 295.1516 - val_mae: 12.8925
Epoch 55/100
23/23 [==============================] - 0s 6ms/step - loss: 247.9039 - mae: 11.8004 - val_loss: 283.7758 - val_mae: 13.2273
Epoch 56/100
23/23 [==============================] - 0s 6ms/step - loss: 265.4812 - mae: 12.2611 - val_loss: 372.7485 - val_mae: 15.8004
Epoch 57/100
23/23 [==============================] - 0s 6ms/step - loss: 224.9263 - mae: 11.0862 - val_loss: 306.0674 - val_mae: 13.9267
Epoch 58/100
23/23 [==============================] - 0s 6ms/step - loss: 243.8710 - mae: 11.7395 - val_loss: 289.5311 - val_mae: 13.4478
Epoch 59/100
23/23 [==============================] - 0s 8ms/step - loss: 218.6981 - mae: 11.0868 - val_loss: 306.4182 - val_mae: 14.2574
Epoch 60/100
23/23 [==============================] - 0s 8ms/step - loss: 214.5573 - mae: 10.9475 - val_loss: 303.7776 - val_mae: 14.0185
Epoch 61/100
23/23 [==============================] - 0s 7ms/step - loss: 221.3008 - mae: 11.1873 - val_loss: 289.7629 - val_mae: 13.5101
Epoch 62/100
23/23 [==============================] - 0s 6ms/step - loss: 240.0028 - mae: 11.5853 - val_loss: 285.9233 - val_mae: 12.2713
Epoch 63/100
23/23 [==============================] - 0s 6ms/step - loss: 216.2903 - mae: 10.9057 - val_loss: 293.3560 - val_mae: 13.4524
Epoch 64/100
23/23 [==============================] - 0s 6ms/step - loss: 214.6038 - mae: 10.7522 - val_loss: 273.8339 - val_mae: 12.4149
Epoch 65/100
23/23 [==============================] - 0s 6ms/step - loss: 193.6740 - mae: 10.4909 - val_loss: 298.6135 - val_mae: 14.0355
Epoch 66/100
23/23 [==============================] - 0s 7ms/step - loss: 192.0968 - mae: 10.4376 - val_loss: 372.0733 - val_mae: 15.6197
Epoch 67/100
23/23 [==============================] - 0s 6ms/step - loss: 219.4713 - mae: 10.7878 - val_loss: 292.7367 - val_mae: 12.0546
Epoch 68/100
23/23 [==============================] - 0s 5ms/step - loss: 220.5655 - mae: 11.0908 - val_loss: 290.2025 - val_mae: 13.5113
Epoch 69/100
23/23 [==============================] - 0s 5ms/step - loss: 211.9885 - mae: 10.9267 - val_loss: 316.6219 - val_mae: 14.1155
Epoch 70/100
23/23 [==============================] - 0s 7ms/step - loss: 223.1383 - mae: 11.3664 - val_loss: 308.2945 - val_mae: 13.7774
Epoch 71/100
23/23 [==============================] - 0s 7ms/step - loss: 195.9216 - mae: 10.6045 - val_loss: 292.8730 - val_mae: 13.3494
Epoch 72/100
23/23 [==============================] - 0s 9ms/step - loss: 202.6668 - mae: 10.5922 - val_loss: 345.4297 - val_mae: 15.3213
Epoch 73/100
23/23 [==============================] - 0s 9ms/step - loss: 203.5939 - mae: 10.9381 - val_loss: 291.2736 - val_mae: 13.0276
Epoch 74/100
23/23 [==============================] - 0s 8ms/step - loss: 238.6126 - mae: 11.4295 - val_loss: 301.1706 - val_mae: 13.6735
Epoch 75/100
23/23 [==============================] - 0s 7ms/step - loss: 221.3391 - mae: 10.8459 - val_loss: 326.5186 - val_mae: 13.7508
Epoch 76/100
23/23 [==============================] - 0s 8ms/step - loss: 237.5428 - mae: 11.2598 - val_loss: 349.7585 - val_mae: 15.4119
Epoch 77/100
23/23 [==============================] - 0s 11ms/step - loss: 218.2746 - mae: 11.1182 - val_loss: 279.8900 - val_mae: 12.5129
Epoch 78/100
23/23 [==============================] - 0s 9ms/step - loss: 203.1976 - mae: 10.6302 - val_loss: 290.4716 - val_mae: 13.1847
Epoch 79/100
23/23 [==============================] - 0s 9ms/step - loss: 211.7428 - mae: 11.2240 - val_loss: 278.5941 - val_mae: 12.9549
Epoch 80/100
23/23 [==============================] - 0s 8ms/step - loss: 201.7664 - mae: 10.7201 - val_loss: 273.7690 - val_mae: 12.5721
Epoch 81/100
23/23 [==============================] - 0s 10ms/step - loss: 194.4387 - mae: 10.3940 - val_loss: 290.3595 - val_mae: 13.1739
Epoch 82/100
23/23 [==============================] - 0s 11ms/step - loss: 217.5407 - mae: 11.0624 - val_loss: 367.9399 - val_mae: 15.7712
Epoch 83/100
23/23 [==============================] - 0s 12ms/step - loss: 205.1880 - mae: 10.7883 - val_loss: 289.7894 - val_mae: 12.4773
Epoch 84/100
23/23 [==============================] - 0s 8ms/step - loss: 229.3287 - mae: 11.4902 - val_loss: 385.3837 - val_mae: 16.2693
Epoch 85/100
23/23 [==============================] - 0s 8ms/step - loss: 194.0652 - mae: 10.4140 - val_loss: 284.4056 - val_mae: 13.2111
Epoch 86/100
23/23 [==============================] - 0s 8ms/step - loss: 197.7741 - mae: 10.8365 - val_loss: 272.0903 - val_mae: 12.4232
Epoch 87/100
23/23 [==============================] - 0s 8ms/step - loss: 211.8458 - mae: 10.7472 - val_loss: 288.5414 - val_mae: 13.2635
Epoch 88/100
23/23 [==============================] - 0s 8ms/step - loss: 196.3691 - mae: 10.4859 - val_loss: 277.2742 - val_mae: 12.8950
Epoch 89/100
23/23 [==============================] - 0s 7ms/step - loss: 197.2737 - mae: 10.2963 - val_loss: 333.0733 - val_mae: 13.2865
Epoch 90/100
23/23 [==============================] - 0s 8ms/step - loss: 203.4127 - mae: 10.6019 - val_loss: 326.2227 - val_mae: 14.7248
Epoch 91/100
23/23 [==============================] - 0s 11ms/step - loss: 196.7898 - mae: 10.3998 - val_loss: 272.1116 - val_mae: 12.5501
Epoch 92/100
23/23 [==============================] - 0s 13ms/step - loss: 183.7110 - mae: 9.9405 - val_loss: 261.6154 - val_mae: 12.0907
Epoch 93/100
23/23 [==============================] - 0s 10ms/step - loss: 182.7839 - mae: 10.3175 - val_loss: 266.3381 - val_mae: 12.1630
Epoch 94/100
23/23 [==============================] - 0s 11ms/step - loss: 216.0041 - mae: 10.7987 - val_loss: 341.7907 - val_mae: 14.7437
Epoch 95/100
23/23 [==============================] - 0s 11ms/step - loss: 194.8896 - mae: 10.5026 - val_loss: 274.3987 - val_mae: 12.6293
Epoch 96/100
23/23 [==============================] - 0s 8ms/step - loss: 195.8411 - mae: 10.3945 - val_loss: 267.7359 - val_mae: 11.7966
Epoch 97/100
23/23 [==============================] - 0s 8ms/step - loss: 180.8604 - mae: 10.0034 - val_loss: 277.1826 - val_mae: 12.8744
Epoch 98/100
23/23 [==============================] - 0s 9ms/step - loss: 162.8801 - mae: 9.3375 - val_loss: 287.8273 - val_mae: 13.2774
Epoch 99/100
23/23 [==============================] - 0s 11ms/step - loss: 199.8849 - mae: 10.3804 - val_loss: 317.0135 - val_mae: 13.6007
Epoch 100/100
23/23 [==============================] - 0s 9ms/step - loss: 209.4151 - mae: 10.4620 - val_loss: 271.4392 - val_mae: 12.2794

In [59]:
y_train_pred = model.predict(X_train)
y_val_pred = model.predict(X_val)
y_test_pred = model.predict(X_test)

train_mse = mean_squared_error(y_train, y_train_pred)
val_mse = mean_squared_error(y_val, y_val_pred)
test_mse = mean_squared_error(y_test, y_test_pred)

print(f"Train MSE: {train_mse}")
print(f"Validation MSE: {val_mse}")
print(f"testing MSE: {test_mse}")

15/15 [==============================] - 0s 2ms/step
4/4 [==============================] - 0s 4ms/step
4/4 [==============================] - 0s 5ms/step
Train MSE: 97.01604302206314
Validation MSE: 261.28914526870943
testing MSE: 271.8676545938636

Với câu trúc này MSE(trainig) < MSE (testing) ==> Hight Variance(overfitting)

Thay đổi cấu trúc của mạng nơ-ron nhân tạo (ANN) bằng cách giảm số lượng nơ-ron trong một lớp thông qua Dropout và sử dụng L2 regularization (Ridge). Đồng thời, sử dụng phương pháp Early Stopping để ngừng huấn luyện sớm khi mô hình không còn cải thiện. Kết quả cho thấy MSE trên cả 3 tập có sự thay đổi tốt hơn, nhưng Train MSE (97.01) vẫn nhỏ hơn nhiều so với Testing MSE(271.86). Mặc dù kết quả đã được cải thiện đáng kể bằng cách sử dụng các phương pháp nhằm giảm variance, mô hình vẫn bị overfitting.

Thử thay đổi opitmizer SGD

In [60]:
model = Sequential()
model.add(Dense(units=128, activation="relu", input_shape=(X_train.shape[1],), kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=64, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=32, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation="relu", kernel_regularizer=l2(0.01)))

model.compile(optimizer=SGD(learning_rate=0.01), loss='mean_squared_error', metrics=['mae'])

model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_28 (Dense)            (None, 128)               1408

 dropout_21 (Dropout)        (None, 128)               0

 dense_29 (Dense)            (None, 64)                8256

 dropout_22 (Dropout)        (None, 64)                0

 dense_30 (Dense)            (None, 32)                2080

 dropout_23 (Dropout)        (None, 32)                0

 dense_31 (Dense)            (None, 1)                 33

=================================================================
Total params: 11777 (46.00 KB)
Trainable params: 11777 (46.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [61]:
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

model.fit(X_train, y_train, epochs=100, batch_size=20, validation_data=(X_val, y_val))

Epoch 1/100
23/23 [==============================] - 1s 14ms/step - loss: 4694.0156 - mae: 46.3546 - val_loss: 4120.9326 - val_mae: 46.0540
Epoch 2/100
23/23 [==============================] - 0s 5ms/step - loss: 3654.4424 - mae: 41.2053 - val_loss: 4108.9321 - val_mae: 46.0540
Epoch 3/100
23/23 [==============================] - 0s 4ms/step - loss: 3642.4944 - mae: 41.2052 - val_loss: 4097.0415 - val_mae: 46.0540
Epoch 4/100
23/23 [==============================] - 0s 5ms/step - loss: 3630.6560 - mae: 41.2052 - val_loss: 4085.2600 - val_mae: 46.0540
Epoch 5/100
23/23 [==============================] - 0s 6ms/step - loss: 3618.9255 - mae: 41.2052 - val_loss: 4073.5864 - val_mae: 46.0540
Epoch 6/100
23/23 [==============================] - 0s 5ms/step - loss: 3607.3037 - mae: 41.2053 - val_loss: 4062.0198 - val_mae: 46.0540
Epoch 7/100
23/23 [==============================] - 0s 6ms/step - loss: 3595.7874 - mae: 41.2052 - val_loss: 4050.5591 - val_mae: 46.0540
Epoch 8/100
23/23 [==============================] - 0s 6ms/step - loss: 3584.3765 - mae: 41.2053 - val_loss: 4039.2029 - val_mae: 46.0540
Epoch 9/100
23/23 [==============================] - 0s 5ms/step - loss: 3573.0713 - mae: 41.2053 - val_loss: 4027.9514 - val_mae: 46.0540
Epoch 10/100
23/23 [==============================] - 0s 5ms/step - loss: 3561.8682 - mae: 41.2052 - val_loss: 4016.8027 - val_mae: 46.0540
Epoch 11/100
23/23 [==============================] - 0s 4ms/step - loss: 3550.7686 - mae: 41.2052 - val_loss: 4005.7561 - val_mae: 46.0540
Epoch 12/100
23/23 [==============================] - 0s 4ms/step - loss: 3539.7698 - mae: 41.2053 - val_loss: 3994.8105 - val_mae: 46.0540
Epoch 13/100
23/23 [==============================] - 0s 5ms/step - loss: 3528.8723 - mae: 41.2053 - val_loss: 3983.9653 - val_mae: 46.0540
Epoch 14/100
23/23 [==============================] - 0s 5ms/step - loss: 3518.0750 - mae: 41.2053 - val_loss: 3973.2190 - val_mae: 46.0540
Epoch 15/100
23/23 [==============================] - 0s 6ms/step - loss: 3507.3752 - mae: 41.2053 - val_loss: 3962.5720 - val_mae: 46.0540
Epoch 16/100
23/23 [==============================] - 0s 6ms/step - loss: 3496.7751 - mae: 41.2052 - val_loss: 3952.0222 - val_mae: 46.0540
Epoch 17/100
23/23 [==============================] - 0s 5ms/step - loss: 3486.2710 - mae: 41.2052 - val_loss: 3941.5686 - val_mae: 46.0540
Epoch 18/100
23/23 [==============================] - 0s 5ms/step - loss: 3475.8638 - mae: 41.2053 - val_loss: 3931.2109 - val_mae: 46.0540
Epoch 19/100
23/23 [==============================] - 0s 5ms/step - loss: 3465.5513 - mae: 41.2052 - val_loss: 3920.9482 - val_mae: 46.0540
Epoch 20/100
23/23 [==============================] - 0s 5ms/step - loss: 3455.3340 - mae: 41.2053 - val_loss: 3910.7793 - val_mae: 46.0540
Epoch 21/100
23/23 [==============================] - 0s 6ms/step - loss: 3445.2092 - mae: 41.2052 - val_loss: 3900.7039 - val_mae: 46.0540
Epoch 22/100
23/23 [==============================] - 0s 5ms/step - loss: 3435.1772 - mae: 41.2052 - val_loss: 3890.7207 - val_mae: 46.0540
Epoch 23/100
23/23 [==============================] - 0s 6ms/step - loss: 3425.2383 - mae: 41.2053 - val_loss: 3880.8286 - val_mae: 46.0540
Epoch 24/100
23/23 [==============================] - 0s 7ms/step - loss: 3415.3892 - mae: 41.2052 - val_loss: 3871.0271 - val_mae: 46.0540
Epoch 25/100
23/23 [==============================] - 0s 5ms/step - loss: 3405.6313 - mae: 41.2053 - val_loss: 3861.3159 - val_mae: 46.0540
Epoch 26/100
23/23 [==============================] - 0s 5ms/step - loss: 3395.9617 - mae: 41.2052 - val_loss: 3851.6936 - val_mae: 46.0540
Epoch 27/100
23/23 [==============================] - 0s 4ms/step - loss: 3386.3816 - mae: 41.2053 - val_loss: 3842.1592 - val_mae: 46.0540
Epoch 28/100
23/23 [==============================] - 0s 5ms/step - loss: 3376.8889 - mae: 41.2053 - val_loss: 3832.7119 - val_mae: 46.0540
Epoch 29/100
23/23 [==============================] - 0s 5ms/step - loss: 3367.4836 - mae: 41.2052 - val_loss: 3823.3513 - val_mae: 46.0540
Epoch 30/100
23/23 [==============================] - 0s 7ms/step - loss: 3358.1636 - mae: 41.2053 - val_loss: 3814.0764 - val_mae: 46.0540
Epoch 31/100
23/23 [==============================] - 0s 7ms/step - loss: 3348.9292 - mae: 41.2053 - val_loss: 3804.8865 - val_mae: 46.0540
Epoch 32/100
23/23 [==============================] - 0s 5ms/step - loss: 3339.7800 - mae: 41.2052 - val_loss: 3795.7805 - val_mae: 46.0540
Epoch 33/100
23/23 [==============================] - 0s 5ms/step - loss: 3330.7136 - mae: 41.2052 - val_loss: 3786.7583 - val_mae: 46.0540
Epoch 34/100
23/23 [==============================] - 0s 5ms/step - loss: 3321.7307 - mae: 41.2053 - val_loss: 3777.8186 - val_mae: 46.0540
Epoch 35/100
23/23 [==============================] - 0s 5ms/step - loss: 3312.8303 - mae: 41.2053 - val_loss: 3768.9604 - val_mae: 46.0540
Epoch 36/100
23/23 [==============================] - 0s 6ms/step - loss: 3304.0107 - mae: 41.2053 - val_loss: 3760.1841 - val_mae: 46.0540
Epoch 37/100
23/23 [==============================] - 0s 8ms/step - loss: 3295.2729 - mae: 41.2053 - val_loss: 3751.4873 - val_mae: 46.0540
Epoch 38/100
23/23 [==============================] - 0s 6ms/step - loss: 3286.6143 - mae: 41.2053 - val_loss: 3742.8708 - val_mae: 46.0540
Epoch 39/100
23/23 [==============================] - 0s 6ms/step - loss: 3278.0352 - mae: 41.2052 - val_loss: 3734.3333 - val_mae: 46.0540
Epoch 40/100
23/23 [==============================] - 0s 5ms/step - loss: 3269.5352 - mae: 41.2053 - val_loss: 3725.8730 - val_mae: 46.0540
Epoch 41/100
23/23 [==============================] - 0s 5ms/step - loss: 3261.1125 - mae: 41.2052 - val_loss: 3717.4915 - val_mae: 46.0540
Epoch 42/100
23/23 [==============================] - 0s 4ms/step - loss: 3252.7668 - mae: 41.2053 - val_loss: 3709.1863 - val_mae: 46.0540
Epoch 43/100
23/23 [==============================] - 0s 5ms/step - loss: 3244.4980 - mae: 41.2052 - val_loss: 3700.9568 - val_mae: 46.0540
Epoch 44/100
23/23 [==============================] - 0s 6ms/step - loss: 3236.3052 - mae: 41.2053 - val_loss: 3692.8027 - val_mae: 46.0540
Epoch 45/100
23/23 [==============================] - 0s 6ms/step - loss: 3228.1873 - mae: 41.2053 - val_loss: 3684.7239 - val_mae: 46.0540
Epoch 46/100
23/23 [==============================] - 0s 6ms/step - loss: 3220.1428 - mae: 41.2053 - val_loss: 3676.7185 - val_mae: 46.0540
Epoch 47/100
23/23 [==============================] - 0s 5ms/step - loss: 3212.1726 - mae: 41.2052 - val_loss: 3668.7864 - val_mae: 46.0540
Epoch 48/100
23/23 [==============================] - 0s 5ms/step - loss: 3204.2759 - mae: 41.2053 - val_loss: 3660.9270 - val_mae: 46.0540
Epoch 49/100
23/23 [==============================] - 0s 4ms/step - loss: 3196.4504 - mae: 41.2052 - val_loss: 3653.1399 - val_mae: 46.0540
Epoch 50/100
23/23 [==============================] - 0s 5ms/step - loss: 3188.6978 - mae: 41.2052 - val_loss: 3645.4238 - val_mae: 46.0540
Epoch 51/100
23/23 [==============================] - 0s 5ms/step - loss: 3181.0156 - mae: 41.2053 - val_loss: 3637.7783 - val_mae: 46.0540
Epoch 52/100
23/23 [==============================] - 0s 7ms/step - loss: 3173.4036 - mae: 41.2053 - val_loss: 3630.2036 - val_mae: 46.0540
Epoch 53/100
23/23 [==============================] - 0s 6ms/step - loss: 3165.8611 - mae: 41.2052 - val_loss: 3622.6973 - val_mae: 46.0540
Epoch 54/100
23/23 [==============================] - 0s 6ms/step - loss: 3158.3887 - mae: 41.2053 - val_loss: 3615.2600 - val_mae: 46.0540
Epoch 55/100
23/23 [==============================] - 0s 6ms/step - loss: 3150.9832 - mae: 41.2053 - val_loss: 3607.8911 - val_mae: 46.0540
Epoch 56/100
23/23 [==============================] - 0s 5ms/step - loss: 3143.6467 - mae: 41.2053 - val_loss: 3600.5896 - val_mae: 46.0540
Epoch 57/100
23/23 [==============================] - 0s 5ms/step - loss: 3136.3772 - mae: 41.2053 - val_loss: 3593.3552 - val_mae: 46.0540
Epoch 58/100
23/23 [==============================] - 0s 5ms/step - loss: 3129.1743 - mae: 41.2053 - val_loss: 3586.1865 - val_mae: 46.0540
Epoch 59/100
23/23 [==============================] - 0s 7ms/step - loss: 3122.0369 - mae: 41.2053 - val_loss: 3579.0840 - val_mae: 46.0540
Epoch 60/100
23/23 [==============================] - 0s 10ms/step - loss: 3114.9656 - mae: 41.2053 - val_loss: 3572.0461 - val_mae: 46.0540
Epoch 61/100
23/23 [==============================] - 0s 9ms/step - loss: 3107.9585 - mae: 41.2053 - val_loss: 3565.0732 - val_mae: 46.0540
Epoch 62/100
23/23 [==============================] - 0s 8ms/step - loss: 3101.0159 - mae: 41.2053 - val_loss: 3558.1636 - val_mae: 46.0540
Epoch 63/100
23/23 [==============================] - 0s 8ms/step - loss: 3094.1370 - mae: 41.2053 - val_loss: 3551.3176 - val_mae: 46.0540
Epoch 64/100
23/23 [==============================] - 0s 11ms/step - loss: 3087.3208 - mae: 41.2053 - val_loss: 3544.5342 - val_mae: 46.0540
Epoch 65/100
23/23 [==============================] - 0s 11ms/step - loss: 3080.5669 - mae: 41.2052 - val_loss: 3537.8132 - val_mae: 46.0540
Epoch 66/100
23/23 [==============================] - 0s 8ms/step - loss: 3073.8755 - mae: 41.2052 - val_loss: 3531.1528 - val_mae: 46.0540
Epoch 67/100
23/23 [==============================] - 0s 8ms/step - loss: 3067.2446 - mae: 41.2053 - val_loss: 3524.5542 - val_mae: 46.0540
Epoch 68/100
23/23 [==============================] - 0s 10ms/step - loss: 3060.6746 - mae: 41.2053 - val_loss: 3518.0161 - val_mae: 46.0540
Epoch 69/100
23/23 [==============================] - 0s 9ms/step - loss: 3054.1655 - mae: 41.2052 - val_loss: 3511.5376 - val_mae: 46.0540
Epoch 70/100
23/23 [==============================] - 0s 8ms/step - loss: 3047.7151 - mae: 41.2053 - val_loss: 3505.1184 - val_mae: 46.0540
Epoch 71/100
23/23 [==============================] - 0s 6ms/step - loss: 3041.3240 - mae: 41.2053 - val_loss: 3498.7583 - val_mae: 46.0540
Epoch 72/100
23/23 [==============================] - 0s 7ms/step - loss: 3034.9915 - mae: 41.2052 - val_loss: 3492.4561 - val_mae: 46.0540
Epoch 73/100
23/23 [==============================] - 0s 8ms/step - loss: 3028.7175 - mae: 41.2052 - val_loss: 3486.2119 - val_mae: 46.0540
Epoch 74/100
23/23 [==============================] - 0s 9ms/step - loss: 3022.5000 - mae: 41.2053 - val_loss: 3480.0247 - val_mae: 46.0540
Epoch 75/100
23/23 [==============================] - 0s 7ms/step - loss: 3016.3403 - mae: 41.2053 - val_loss: 3473.8943 - val_mae: 46.0540
Epoch 76/100
23/23 [==============================] - 0s 6ms/step - loss: 3010.2363 - mae: 41.2053 - val_loss: 3467.8201 - val_mae: 46.0540
Epoch 77/100
23/23 [==============================] - 0s 6ms/step - loss: 3004.1887 - mae: 41.2052 - val_loss: 3461.8010 - val_mae: 46.0540
Epoch 78/100
23/23 [==============================] - 0s 6ms/step - loss: 2998.1963 - mae: 41.2052 - val_loss: 3455.8381 - val_mae: 46.0540
Epoch 79/100
23/23 [==============================] - 0s 10ms/step - loss: 2992.2588 - mae: 41.2053 - val_loss: 3449.9290 - val_mae: 46.0540
Epoch 80/100
23/23 [==============================] - 0s 8ms/step - loss: 2986.3757 - mae: 41.2053 - val_loss: 3444.0740 - val_mae: 46.0540
Epoch 81/100
23/23 [==============================] - 0s 8ms/step - loss: 2980.5469 - mae: 41.2053 - val_loss: 3438.2727 - val_mae: 46.0540
Epoch 82/100
23/23 [==============================] - 0s 7ms/step - loss: 2974.7712 - mae: 41.2052 - val_loss: 3432.5247 - val_mae: 46.0540
Epoch 83/100
23/23 [==============================] - 0s 7ms/step - loss: 2969.0481 - mae: 41.2052 - val_loss: 3426.8296 - val_mae: 46.0540
Epoch 84/100
23/23 [==============================] - 0s 8ms/step - loss: 2963.3777 - mae: 41.2052 - val_loss: 3421.1863 - val_mae: 46.0540
Epoch 85/100
23/23 [==============================] - 0s 10ms/step - loss: 2957.7595 - mae: 41.2052 - val_loss: 3415.5947 - val_mae: 46.0540
Epoch 86/100
23/23 [==============================] - 0s 10ms/step - loss: 2952.1924 - mae: 41.2052 - val_loss: 3410.0542 - val_mae: 46.0540
Epoch 87/100
23/23 [==============================] - 0s 10ms/step - loss: 2946.6760 - mae: 41.2052 - val_loss: 3404.5645 - val_mae: 46.0540
Epoch 88/100
23/23 [==============================] - 0s 10ms/step - loss: 2941.2107 - mae: 41.2053 - val_loss: 3399.1257 - val_mae: 46.0540
Epoch 89/100
23/23 [==============================] - 0s 10ms/step - loss: 2935.7949 - mae: 41.2053 - val_loss: 3393.7356 - val_mae: 46.0540
Epoch 90/100
23/23 [==============================] - 0s 9ms/step - loss: 2930.4290 - mae: 41.2052 - val_loss: 3388.3958 - val_mae: 46.0540
Epoch 91/100
23/23 [==============================] - 0s 8ms/step - loss: 2925.1118 - mae: 41.2052 - val_loss: 3383.1042 - val_mae: 46.0540
Epoch 92/100
23/23 [==============================] - 0s 7ms/step - loss: 2919.8442 - mae: 41.2052 - val_loss: 3377.8618 - val_mae: 46.0540
Epoch 93/100
23/23 [==============================] - 0s 5ms/step - loss: 2914.6243 - mae: 41.2053 - val_loss: 3372.6667 - val_mae: 46.0540
Epoch 94/100
23/23 [==============================] - 0s 5ms/step - loss: 2909.4524 - mae: 41.2052 - val_loss: 3367.5195 - val_mae: 46.0540
Epoch 95/100
23/23 [==============================] - 0s 6ms/step - loss: 2904.3279 - mae: 41.2053 - val_loss: 3362.4194 - val_mae: 46.0540
Epoch 96/100
23/23 [==============================] - 0s 5ms/step - loss: 2899.2498 - mae: 41.2053 - val_loss: 3357.3662 - val_mae: 46.0540
Epoch 97/100
23/23 [==============================] - 0s 5ms/step - loss: 2894.2185 - mae: 41.2052 - val_loss: 3352.3591 - val_mae: 46.0540
Epoch 98/100
23/23 [==============================] - 0s 6ms/step - loss: 2889.2332 - mae: 41.2052 - val_loss: 3347.3979 - val_mae: 46.0540
Epoch 99/100
23/23 [==============================] - 0s 6ms/step - loss: 2884.2939 - mae: 41.2052 - val_loss: 3342.4824 - val_mae: 46.0540
Epoch 100/100
23/23 [==============================] - 0s 6ms/step - loss: 2879.3999 - mae: 41.2053 - val_loss: 3337.6113 - val_mae: 46.0540

In [62]:
y_train_pred = model.predict(X_train)
y_val_pred = model.predict(X_val)
y_test_pred = model.predict(X_test)

train_mse = mean_squared_error(y_train, y_train_pred)
val_mse = mean_squared_error(y_val, y_val_pred)
test_mse = mean_squared_error(y_test, y_test_pred)

print(f"Train MSE: {train_mse}")
print(f"Validation MSE: {val_mse}")
print(f"testing MSE: {test_mse}")

15/15 [==============================] - 0s 3ms/step
4/4 [==============================] - 0s 4ms/step
4/4 [==============================] - 0s 4ms/step
Train MSE: 2349.9139322440087
Validation MSE: 2810.66834040404
testing MSE: 2492.264584848485

khi thay đổi SGD opitmizer ta nhận thấy model không tốt với SGD, tiếp tục thay đổi thử với Nadam

In [63]:
model = Sequential()
model.add(Dense(units=128, activation="relu", input_shape=(X_train.shape[1],), kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=64, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=32, activation="relu", kernel_regularizer=l2(0.01)))
model.add(Dropout(0.2))
model.add(Dense(units=1, activation="relu", kernel_regularizer=l2(0.01)))

model.compile(optimizer=Nadam(learning_rate=0.01), loss='mean_squared_error', metrics=['mae'])

model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_32 (Dense)            (None, 128)               1408

 dropout_24 (Dropout)        (None, 128)               0

 dense_33 (Dense)            (None, 64)                8256

 dropout_25 (Dropout)        (None, 64)                0

 dense_34 (Dense)            (None, 32)                2080

 dropout_26 (Dropout)        (None, 32)                0

 dense_35 (Dense)            (None, 1)                 33

=================================================================
Total params: 11777 (46.00 KB)
Trainable params: 11777 (46.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [64]:
early_stopping = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)

model.fit(X_train, y_train, epochs=100, batch_size=20, validation_data=(X_val, y_val))

Epoch 1/100
23/23 [==============================] - 2s 15ms/step - loss: 1209.0963 - mae: 26.9045 - val_loss: 328.3438 - val_mae: 14.6992
Epoch 2/100
23/23 [==============================] - 0s 5ms/step - loss: 408.4292 - mae: 16.0125 - val_loss: 291.1360 - val_mae: 13.7406
Epoch 3/100
23/23 [==============================] - 0s 5ms/step - loss: 375.2122 - mae: 15.1979 - val_loss: 291.9458 - val_mae: 14.1646
Epoch 4/100
23/23 [==============================] - 0s 5ms/step - loss: 365.5896 - mae: 15.0137 - val_loss: 272.7919 - val_mae: 12.8725
Epoch 5/100
23/23 [==============================] - 0s 6ms/step - loss: 342.9194 - mae: 14.6821 - val_loss: 313.0564 - val_mae: 14.3769
Epoch 6/100
23/23 [==============================] - 0s 7ms/step - loss: 347.9775 - mae: 14.4734 - val_loss: 306.2778 - val_mae: 14.2564
Epoch 7/100
23/23 [==============================] - 0s 6ms/step - loss: 311.5587 - mae: 13.6013 - val_loss: 294.9350 - val_mae: 13.9962
Epoch 8/100
23/23 [==============================] - 0s 8ms/step - loss: 350.5030 - mae: 14.6043 - val_loss: 337.8940 - val_mae: 15.3865
Epoch 9/100
23/23 [==============================] - 0s 8ms/step - loss: 341.9380 - mae: 14.5470 - val_loss: 295.9334 - val_mae: 13.8583
Epoch 10/100
23/23 [==============================] - 0s 6ms/step - loss: 341.8221 - mae: 14.6085 - val_loss: 269.0473 - val_mae: 13.0301
Epoch 11/100
23/23 [==============================] - 0s 6ms/step - loss: 293.4708 - mae: 13.2656 - val_loss: 282.4973 - val_mae: 12.6660
Epoch 12/100
23/23 [==============================] - 0s 8ms/step - loss: 337.7124 - mae: 14.4003 - val_loss: 276.7385 - val_mae: 12.7550
Epoch 13/100
23/23 [==============================] - 0s 6ms/step - loss: 305.4824 - mae: 13.6250 - val_loss: 279.1145 - val_mae: 13.7435
Epoch 14/100
23/23 [==============================] - 0s 8ms/step - loss: 277.0135 - mae: 12.8860 - val_loss: 268.3416 - val_mae: 13.1075
Epoch 15/100
23/23 [==============================] - 0s 6ms/step - loss: 287.7856 - mae: 12.8173 - val_loss: 298.3146 - val_mae: 14.1294
Epoch 16/100
23/23 [==============================] - 0s 6ms/step - loss: 303.8727 - mae: 13.5772 - val_loss: 313.3059 - val_mae: 14.4900
Epoch 17/100
23/23 [==============================] - 0s 6ms/step - loss: 279.4097 - mae: 12.7419 - val_loss: 263.6034 - val_mae: 12.8097
Epoch 18/100
23/23 [==============================] - 0s 5ms/step - loss: 259.0915 - mae: 12.3516 - val_loss: 354.1224 - val_mae: 15.6868
Epoch 19/100
23/23 [==============================] - 0s 6ms/step - loss: 279.7103 - mae: 12.6536 - val_loss: 260.8541 - val_mae: 12.3617
Epoch 20/100
23/23 [==============================] - 0s 6ms/step - loss: 275.7763 - mae: 12.6530 - val_loss: 308.1350 - val_mae: 14.2887
Epoch 21/100
23/23 [==============================] - 0s 6ms/step - loss: 290.8167 - mae: 12.9752 - val_loss: 262.4873 - val_mae: 12.7646
Epoch 22/100
23/23 [==============================] - 0s 5ms/step - loss: 304.7510 - mae: 13.0660 - val_loss: 271.8242 - val_mae: 13.1652
Epoch 23/100
23/23 [==============================] - 0s 6ms/step - loss: 281.0660 - mae: 12.9315 - val_loss: 285.0744 - val_mae: 13.5280
Epoch 24/100
23/23 [==============================] - 0s 5ms/step - loss: 294.5723 - mae: 12.8306 - val_loss: 307.0396 - val_mae: 14.3677
Epoch 25/100
23/23 [==============================] - 0s 5ms/step - loss: 242.5622 - mae: 12.0823 - val_loss: 279.4848 - val_mae: 13.4120
Epoch 26/100
23/23 [==============================] - 0s 6ms/step - loss: 285.8736 - mae: 12.7553 - val_loss: 278.0418 - val_mae: 13.3193
Epoch 27/100
23/23 [==============================] - 0s 5ms/step - loss: 258.5119 - mae: 12.5491 - val_loss: 269.4357 - val_mae: 13.0510
Epoch 28/100
23/23 [==============================] - 0s 6ms/step - loss: 233.0181 - mae: 11.7794 - val_loss: 262.6106 - val_mae: 12.6477
Epoch 29/100
23/23 [==============================] - 0s 6ms/step - loss: 238.2255 - mae: 11.6633 - val_loss: 270.0210 - val_mae: 12.8781
Epoch 30/100
23/23 [==============================] - 0s 5ms/step - loss: 261.0266 - mae: 12.2322 - val_loss: 273.9439 - val_mae: 12.1826
Epoch 31/100
23/23 [==============================] - 0s 5ms/step - loss: 276.8777 - mae: 12.5073 - val_loss: 284.8593 - val_mae: 13.1084
Epoch 32/100
23/23 [==============================] - 0s 6ms/step - loss: 249.9148 - mae: 11.8371 - val_loss: 263.7868 - val_mae: 12.6731
Epoch 33/100
23/23 [==============================] - 0s 7ms/step - loss: 252.7922 - mae: 12.0975 - val_loss: 295.7648 - val_mae: 13.1273
Epoch 34/100
23/23 [==============================] - 0s 6ms/step - loss: 236.6574 - mae: 11.6465 - val_loss: 250.6501 - val_mae: 11.9193
Epoch 35/100
23/23 [==============================] - 0s 8ms/step - loss: 267.3057 - mae: 12.4120 - val_loss: 277.6465 - val_mae: 13.2656
Epoch 36/100
23/23 [==============================] - 0s 6ms/step - loss: 243.3174 - mae: 11.8427 - val_loss: 248.0361 - val_mae: 12.0219
Epoch 37/100
23/23 [==============================] - 0s 7ms/step - loss: 229.8174 - mae: 11.5109 - val_loss: 282.0089 - val_mae: 13.1909
Epoch 38/100
23/23 [==============================] - 0s 6ms/step - loss: 227.5936 - mae: 11.1541 - val_loss: 289.2715 - val_mae: 13.6639
Epoch 39/100
23/23 [==============================] - 0s 7ms/step - loss: 225.7193 - mae: 11.3831 - val_loss: 280.1293 - val_mae: 12.4236
Epoch 40/100
23/23 [==============================] - 0s 13ms/step - loss: 223.5587 - mae: 11.2262 - val_loss: 316.5918 - val_mae: 14.2720
Epoch 41/100
23/23 [==============================] - 0s 12ms/step - loss: 233.9595 - mae: 11.4972 - val_loss: 292.3270 - val_mae: 13.2799
Epoch 42/100
23/23 [==============================] - 0s 11ms/step - loss: 264.0916 - mae: 11.9739 - val_loss: 255.8163 - val_mae: 12.2073
Epoch 43/100
23/23 [==============================] - 0s 10ms/step - loss: 231.8617 - mae: 11.5581 - val_loss: 260.5543 - val_mae: 12.5003
Epoch 44/100
23/23 [==============================] - 0s 15ms/step - loss: 241.2533 - mae: 11.5836 - val_loss: 252.5038 - val_mae: 11.9457
Epoch 45/100
23/23 [==============================] - 0s 11ms/step - loss: 238.1316 - mae: 11.4643 - val_loss: 260.2319 - val_mae: 12.4790
Epoch 46/100
23/23 [==============================] - 0s 10ms/step - loss: 247.8154 - mae: 12.0389 - val_loss: 317.8359 - val_mae: 14.3121
Epoch 47/100
23/23 [==============================] - 0s 11ms/step - loss: 236.7353 - mae: 11.6270 - val_loss: 271.0698 - val_mae: 13.2635
Epoch 48/100
23/23 [==============================] - 0s 12ms/step - loss: 203.4283 - mae: 10.6068 - val_loss: 260.7974 - val_mae: 12.7358
Epoch 49/100
23/23 [==============================] - 0s 11ms/step - loss: 231.4530 - mae: 11.5424 - val_loss: 288.6979 - val_mae: 12.7615
Epoch 50/100
23/23 [==============================] - 0s 9ms/step - loss: 218.3700 - mae: 11.0194 - val_loss: 288.9221 - val_mae: 13.4060
Epoch 51/100
23/23 [==============================] - 0s 9ms/step - loss: 210.8668 - mae: 10.7647 - val_loss: 251.4274 - val_mae: 11.8401
Epoch 52/100
23/23 [==============================] - 0s 12ms/step - loss: 255.9794 - mae: 11.8959 - val_loss: 290.3062 - val_mae: 13.6164
Epoch 53/100
23/23 [==============================] - 0s 10ms/step - loss: 240.0812 - mae: 11.4863 - val_loss: 295.3374 - val_mae: 13.8029
Epoch 54/100
23/23 [==============================] - 0s 9ms/step - loss: 238.8192 - mae: 11.7531 - val_loss: 292.9456 - val_mae: 13.6083
Epoch 55/100
23/23 [==============================] - 0s 9ms/step - loss: 221.8300 - mae: 11.3513 - val_loss: 266.1997 - val_mae: 12.8130
Epoch 56/100
23/23 [==============================] - 0s 11ms/step - loss: 219.7291 - mae: 11.0308 - val_loss: 266.4641 - val_mae: 12.4635
Epoch 57/100
23/23 [==============================] - 0s 9ms/step - loss: 201.6066 - mae: 10.4150 - val_loss: 257.9980 - val_mae: 12.3859
Epoch 58/100
23/23 [==============================] - 0s 9ms/step - loss: 207.7614 - mae: 10.8026 - val_loss: 251.2679 - val_mae: 12.1484
Epoch 59/100
23/23 [==============================] - 0s 10ms/step - loss: 209.7642 - mae: 10.6696 - val_loss: 280.4777 - val_mae: 13.2779
Epoch 60/100
23/23 [==============================] - 0s 11ms/step - loss: 211.4973 - mae: 11.0819 - val_loss: 260.9073 - val_mae: 12.6893
Epoch 61/100
23/23 [==============================] - 0s 13ms/step - loss: 212.7947 - mae: 11.0851 - val_loss: 249.4779 - val_mae: 11.9905
Epoch 62/100
23/23 [==============================] - 0s 10ms/step - loss: 228.1051 - mae: 11.2720 - val_loss: 263.1662 - val_mae: 12.4547
Epoch 63/100
23/23 [==============================] - 0s 11ms/step - loss: 225.1900 - mae: 11.2039 - val_loss: 313.1549 - val_mae: 14.1730
Epoch 64/100
23/23 [==============================] - 0s 8ms/step - loss: 230.0449 - mae: 11.3756 - val_loss: 312.4052 - val_mae: 14.4389
Epoch 65/100
23/23 [==============================] - 0s 8ms/step - loss: 227.7992 - mae: 11.4527 - val_loss: 253.8640 - val_mae: 11.7819
Epoch 66/100
23/23 [==============================] - 0s 7ms/step - loss: 212.1151 - mae: 10.6971 - val_loss: 324.2606 - val_mae: 14.2015
Epoch 67/100
23/23 [==============================] - 0s 6ms/step - loss: 211.0091 - mae: 10.8868 - val_loss: 343.1754 - val_mae: 14.8396
Epoch 68/100
23/23 [==============================] - 0s 6ms/step - loss: 200.4206 - mae: 10.6318 - val_loss: 288.7150 - val_mae: 13.4090
Epoch 69/100
23/23 [==============================] - 0s 6ms/step - loss: 216.3526 - mae: 10.9941 - val_loss: 287.8228 - val_mae: 13.1008
Epoch 70/100
23/23 [==============================] - 0s 7ms/step - loss: 245.0087 - mae: 11.6618 - val_loss: 287.9654 - val_mae: 12.7551
Epoch 71/100
23/23 [==============================] - 0s 6ms/step - loss: 212.4802 - mae: 10.8227 - val_loss: 260.0579 - val_mae: 12.2099
Epoch 72/100
23/23 [==============================] - 0s 6ms/step - loss: 206.3072 - mae: 10.7040 - val_loss: 305.5824 - val_mae: 13.6904
Epoch 73/100
23/23 [==============================] - 0s 6ms/step - loss: 223.3767 - mae: 11.1134 - val_loss: 348.1263 - val_mae: 15.3907
Epoch 74/100
23/23 [==============================] - 0s 5ms/step - loss: 195.7138 - mae: 10.3491 - val_loss: 283.4171 - val_mae: 12.4163
Epoch 75/100
23/23 [==============================] - 0s 6ms/step - loss: 209.0589 - mae: 10.8342 - val_loss: 288.3104 - val_mae: 12.9480
Epoch 76/100
23/23 [==============================] - 0s 6ms/step - loss: 205.1366 - mae: 10.4921 - val_loss: 268.9469 - val_mae: 12.5347
Epoch 77/100
23/23 [==============================] - 0s 8ms/step - loss: 190.8750 - mae: 10.3239 - val_loss: 316.5497 - val_mae: 14.1137
Epoch 78/100
23/23 [==============================] - 0s 8ms/step - loss: 228.9776 - mae: 11.3766 - val_loss: 309.5501 - val_mae: 13.8708
Epoch 79/100
23/23 [==============================] - 0s 7ms/step - loss: 196.6457 - mae: 10.5214 - val_loss: 278.1130 - val_mae: 11.7904
Epoch 80/100
23/23 [==============================] - 0s 6ms/step - loss: 191.8985 - mae: 10.5186 - val_loss: 272.5851 - val_mae: 12.5326
Epoch 81/100
23/23 [==============================] - 0s 5ms/step - loss: 213.8301 - mae: 10.9616 - val_loss: 338.6636 - val_mae: 14.9854
Epoch 82/100
23/23 [==============================] - 0s 5ms/step - loss: 187.5733 - mae: 10.0205 - val_loss: 293.1776 - val_mae: 13.3978
Epoch 83/100
23/23 [==============================] - 0s 6ms/step - loss: 207.9496 - mae: 10.7467 - val_loss: 275.5278 - val_mae: 12.5568
Epoch 84/100
23/23 [==============================] - 0s 7ms/step - loss: 202.8855 - mae: 10.5632 - val_loss: 355.1009 - val_mae: 15.0277
Epoch 85/100
23/23 [==============================] - 0s 5ms/step - loss: 224.0814 - mae: 10.9739 - val_loss: 296.2720 - val_mae: 13.5252
Epoch 86/100
23/23 [==============================] - 0s 5ms/step - loss: 198.0812 - mae: 10.3675 - val_loss: 287.9237 - val_mae: 12.2713
Epoch 87/100
23/23 [==============================] - 0s 6ms/step - loss: 191.6376 - mae: 10.3480 - val_loss: 265.2197 - val_mae: 12.2401
Epoch 88/100
23/23 [==============================] - 0s 5ms/step - loss: 184.5146 - mae: 10.0805 - val_loss: 280.7729 - val_mae: 12.8275
Epoch 89/100
23/23 [==============================] - 0s 5ms/step - loss: 188.0136 - mae: 10.0829 - val_loss: 271.9698 - val_mae: 12.7457
Epoch 90/100
23/23 [==============================] - 0s 5ms/step - loss: 178.2486 - mae: 9.9891 - val_loss: 261.0954 - val_mae: 12.3443
Epoch 91/100
23/23 [==============================] - 0s 7ms/step - loss: 184.2550 - mae: 10.1200 - val_loss: 296.4458 - val_mae: 13.1195
Epoch 92/100
23/23 [==============================] - 0s 6ms/step - loss: 192.1838 - mae: 10.1186 - val_loss: 299.6385 - val_mae: 12.5145
Epoch 93/100
23/23 [==============================] - 0s 5ms/step - loss: 210.4408 - mae: 10.7925 - val_loss: 304.6056 - val_mae: 13.6184
Epoch 94/100
23/23 [==============================] - 0s 6ms/step - loss: 196.4607 - mae: 10.4847 - val_loss: 264.6906 - val_mae: 12.1193
Epoch 95/100
23/23 [==============================] - 0s 6ms/step - loss: 182.3068 - mae: 9.9096 - val_loss: 290.5223 - val_mae: 13.2168
Epoch 96/100
23/23 [==============================] - 0s 5ms/step - loss: 181.5503 - mae: 9.8935 - val_loss: 286.6150 - val_mae: 13.1390
Epoch 97/100
23/23 [==============================] - 0s 6ms/step - loss: 182.3762 - mae: 9.8798 - val_loss: 306.0900 - val_mae: 14.1977
Epoch 98/100
23/23 [==============================] - 0s 7ms/step - loss: 190.6583 - mae: 10.3006 - val_loss: 272.0490 - val_mae: 13.0949
Epoch 99/100
23/23 [==============================] - 0s 6ms/step - loss: 190.2791 - mae: 10.2813 - val_loss: 285.9604 - val_mae: 13.3644
Epoch 100/100
23/23 [==============================] - 0s 6ms/step - loss: 179.1934 - mae: 9.8217 - val_loss: 321.5478 - val_mae: 14.1415

In [65]:
y_train_pred = model.predict(X_train)
y_val_pred = model.predict(X_val)
y_test_pred = model.predict(X_test)

train_mse = mean_squared_error(y_train, y_train_pred)
val_mse = mean_squared_error(y_val, y_val_pred)
test_mse = mean_squared_error(y_test, y_test_pred)

print(f"Train MSE: {train_mse}")
print(f"Validation MSE: {val_mse}")
print(f"testing MSE: {test_mse}")

15/15 [==============================] - 0s 2ms/step
4/4 [==============================] - 0s 4ms/step
4/4 [==============================] - 0s 4ms/step
Train MSE: 123.1034413327308
Validation MSE: 309.8252849014843
testing MSE: 260.4227678308558

Mặc dù đã áp dụng các kỹ thuật như Dropout và L2 regularization, mô hình vẫn có dấu hiệu overfitting. MSE trên tập huấn luyện nhỏ hơn nhiều so với trên tập validation và tập test giống như Adam. Nếu tiếp tục điều chỉnh các hyperparameters thì khả năng mô hình sẽ học tốt hơn

Chuyển qua bộ Thiên Ưu dataset

In [66]:
file_path = '/content/drive/MyDrive/Colab Notebooks/Thien_Uu.csv'
df = pd.read_csv(file_path)
df.head()

,GIST_0,GIST_1,GIST_2,GIST_3,GIST_4,GIST_5,GIST_6,GIST_7,GIST_8,GIST_9,...,GIST_119,GIST_120,GIST_121,GIST_122,GIST_123,GIST_124,GIST_125,GIST_126,GIST_127,class
0,0.001387,0.000820,0.001319,0.000786,0.001090,0.001229,0.001423,0.001787,0.001208,0.017221,...,0.001520,0.001119,0.001531,0.006161,0.002631,0.002506,0.033151,0.024942,0.002070,positive
1,0.014555,0.028314,0.026516,0.004162,0.001652,0.001647,0.004622,0.012038,0.002175,0.034284,...,0.006209,0.000769,0.001208,0.001088,0.000918,0.001917,0.011253,0.050512,0.004258,positive
2,0.002258,0.009734,0.001074,0.001196,0.001346,0.000902,0.001010,0.001091,0.003414,0.046807,...,0.001990,0.000785,0.003204,0.008465,0.007019,0.000827,0.013845,0.047319,0.001672,positive
3,0.000959,0.001216,0.002057,0.001346,0.001068,0.001529,0.001984,0.001013,0.001332,0.002051,...,0.002557,0.001676,0.000775,0.000469,0.000762,0.002117,0.028958,0.031339,0.001867,positive
4,0.001517,0.000951,0.000973,0.001367,0.001424,0.000976,0.001300,0.001189,0.001418,0.002512,...,0.003148,0.001907,0.003551,0.002413,0.003461,0.002297,0.022082,0.041486,0.001978,positive

In [67]:
X = df.drop(columns=['class'])
y = df['class']

le = LabelEncoder()
y = le.fit_transform(y)

In [68]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_val_scaled = scaler.fit_transform(X_val)
X_test_scaled = scaler.fit_transform(X_test)

In [69]:
model = Sequential()
model.add(Dense(units=128, activation='relu', input_shape=(X_train.shape[1],),kernel_regularizer=l2(0.01)))
model.add(Dense(units=64, activation='relu', kernel_regularizer=l2(0.01)))
model.add(Dense(units=32, activation='relu', kernel_regularizer=l2(0.01)))
model.add(Dense(units=1, activation='sigmoid', kernel_regularizer=l2(0.01)))

model.compile(optimizer = Adam(learning_rate=0.01), loss='binary_crossentropy', metrics=['accuracy'])

model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_36 (Dense)            (None, 128)               16512

 dense_37 (Dense)            (None, 64)                8256

 dense_38 (Dense)            (None, 32)                2080

 dense_39 (Dense)            (None, 1)                 33

=================================================================
Total params: 26881 (105.00 KB)
Trainable params: 26881 (105.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [70]:
call_back = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

model.fit(X_train_scaled,
          y_train,
          epochs=200,
          batch_size=16,
          validation_data=(X_val_scaled, y_val),
          callbacks = [call_back],
          verbose = 1)

Epoch 1/200
88/88 [==============================] - 2s 10ms/step - loss: 1.0610 - accuracy: 0.8554 - val_loss: 0.5482 - val_accuracy: 0.8904
Epoch 2/200
88/88 [==============================] - 1s 6ms/step - loss: 0.5062 - accuracy: 0.8739 - val_loss: 0.4102 - val_accuracy: 0.9302
Epoch 3/200
88/88 [==============================] - 1s 16ms/step - loss: 0.4301 - accuracy: 0.8974 - val_loss: 0.4326 - val_accuracy: 0.8904
Epoch 4/200
88/88 [==============================] - 1s 12ms/step - loss: 0.3943 - accuracy: 0.9053 - val_loss: 0.3725 - val_accuracy: 0.9203
Epoch 5/200
88/88 [==============================] - 1s 11ms/step - loss: 0.3735 - accuracy: 0.9103 - val_loss: 0.3761 - val_accuracy: 0.9236
Epoch 6/200
88/88 [==============================] - 0s 6ms/step - loss: 0.3520 - accuracy: 0.9181 - val_loss: 0.3723 - val_accuracy: 0.9037
Epoch 7/200
88/88 [==============================] - 1s 6ms/step - loss: 0.3487 - accuracy: 0.9202 - val_loss: 0.3916 - val_accuracy: 0.9203
Epoch 8/200
88/88 [==============================] - 1s 8ms/step - loss: 0.3491 - accuracy: 0.9217 - val_loss: 0.3321 - val_accuracy: 0.9369
Epoch 9/200
88/88 [==============================] - 0s 4ms/step - loss: 0.3250 - accuracy: 0.9316 - val_loss: 0.3197 - val_accuracy: 0.9369
Epoch 10/200
88/88 [==============================] - 0s 3ms/step - loss: 0.3296 - accuracy: 0.9288 - val_loss: 0.3632 - val_accuracy: 0.8937
Epoch 11/200
88/88 [==============================] - 0s 4ms/step - loss: 0.3214 - accuracy: 0.9295 - val_loss: 0.3335 - val_accuracy: 0.9136
Epoch 12/200
88/88 [==============================] - 0s 4ms/step - loss: 0.3309 - accuracy: 0.9302 - val_loss: 0.3430 - val_accuracy: 0.9203
Epoch 13/200
88/88 [==============================] - 0s 4ms/step - loss: 0.3232 - accuracy: 0.9274 - val_loss: 0.3362 - val_accuracy: 0.9336
Epoch 14/200
88/88 [==============================] - 1s 6ms/step - loss: 0.3112 - accuracy: 0.9338 - val_loss: 0.3221 - val_accuracy: 0.9336
Epoch 15/200
88/88 [==============================] - 0s 5ms/step - loss: 0.3124 - accuracy: 0.9309 - val_loss: 0.4006 - val_accuracy: 0.9037
Epoch 16/200
88/88 [==============================] - 0s 5ms/step - loss: 0.3087 - accuracy: 0.9316 - val_loss: 0.3251 - val_accuracy: 0.9203
Epoch 17/200
88/88 [==============================] - 0s 4ms/step - loss: 0.3237 - accuracy: 0.9274 - val_loss: 0.3463 - val_accuracy: 0.9236
Epoch 18/200
88/88 [==============================] - 0s 5ms/step - loss: 0.3256 - accuracy: 0.9224 - val_loss: 0.3238 - val_accuracy: 0.9236
Epoch 19/200
88/88 [==============================] - 0s 4ms/step - loss: 0.3350 - accuracy: 0.9231 - val_loss: 0.3415 - val_accuracy: 0.9203

In [71]:
train_loss, train_acc = model.evaluate(X_train_scaled, y_train, verbose=0)
val_loss, val_acc = model.evaluate(X_val_scaled, y_val, verbose=0)
test_loss, test_acc = model.evaluate(X_test_scaled, y_test, verbose=0)

print(f"Acc on Training set: {train_acc * 100:2f}%")
print(f"Acc on validation set: {val_acc * 100:2f}%")
print(f"Acc on Test set: {test_acc * 100:2f}%")

Acc on Training set: 94.515669%
Acc on validation set: 93.687707%
Acc on Test set: 93.687707%

Dựa vào kết quả trên, ta thấy sự khác biệt giữa accuracy của tập Train và Test không quá lớn, khoảng 1-2%. Điều này cho thấy mô hình không có dấu hiệu overfitting rõ ràng. Việc thay đổi kiến trúc và sử dụng hợp lý các hyperparameter đã giúp đạt được độ chính xác của tập Train khá cao (94.51%) và độ chính xác của tập kiểm tra (93.68%). So sánh độ chính xác trên ba tập dữ liệu đều tương đối cao và không có sự chênh lệch lớn, do đó mô hình không có dấu hiệu của underfitting (high bias).

Với việc thay đổi kiến trúc của mạng ANN và việc sử dụng và thay đổi các giá trị của hyper parameter (learning rate, epochs và regularization,.....) thì mô hình sẽ dần đạt kết quả tốt nhất